[package]
name = "ironsmith-compiler-source"
version = "0.1.0"
edition = "2024"

[dependencies]
ironsmith-compiler-api = { path = "../ironsmith-compiler-api", default-features = false }
ironsmith-compiler-syntax = { path = "../ironsmith-compiler-syntax", default-features = false }

[features]
default = []

[lib]
path = "src/lib.rs"
