[workspace]
members = [
    "crates/ironsmith-core",
    "crates/ironsmith-runtime",
    "crates/ironsmith-compiler",
    "crates/ironsmith-registry",
    "crates/ironsmith-wasm",
    "crates/ironsmith-cli",
    "crates/ironsmith-tools",
    "crates/ironsmith-audit",
]
default-members = [
    "crates/ironsmith-core",
    "crates/ironsmith-runtime",
    "crates/ironsmith-compiler",
    # "crates/ironsmith-registry",
    # "crates/ironsmith-wasm",
    # "crates/ironsmith-cli",
]
resolver = "2"
