[package]
name = "ironsmith-verifier-shard-38-49"
version = "0.1.0"
edition = "2024"
[dependencies]
ironsmith-verifier-ziffle = { path = "../ironsmith-verifier-ziffle", default-features = false }
ironsmith-verifier-shard-38-43 = { path = "../ironsmith-verifier-shard-38-43", default-features = false }
ironsmith-verifier-shard-44-49 = { path = "../ironsmith-verifier-shard-44-49", default-features = false }
[features]
default = []
