[package]
name = "ironsmith-registry"
version = "0.1.0"
edition = "2024"

[features]
default = ["handwritten-parse-support"]
handwritten-parse-support = []

[dependencies]
ironsmith-core = { path = "../ironsmith-core" }
ironsmith = { package = "ironsmith-runtime", path = "../ironsmith-runtime", features = ["compiler-integration"] }
ironsmith-compiler = { path = "../ironsmith-compiler" }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
path = "src/lib.rs"
