//! Versioned exact replacement predicates with explicit captured snapshot conversion.
//! The owning occurrence-table codec supplies graph-bound executable snapshots.
use crate::events::ReplacementMatcher as _;
use crate::replacement_matcher_descriptor::{NativeReplacementMatcherDescriptor,ReplacementMatcherDescriptor as Native};
pub const REPLACEMENT_MATCHER_CODEC_VERSION:u32=1;
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields, bound(serialize="S:serde::Serialize",deserialize="S:serde::Deserialize<'de>"))]
pub struct RetainedReplacementMatcher<S> { pub version:u32, pub predicate:RetainedReplacementMatcherPredicate<S> }
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag="kind",content="payload",deny_unknown_fields,bound(serialize="S:serde::Serialize",deserialize="S:serde::Deserialize<'de>"))]
pub enum RetainedReplacementMatcherPredicate<S> {
DamageToSpecificTargetMatcher { target: crate::events::DamageTarget },
DamageSourceToSpecificTargetMatcher { source: crate::events::damage::matchers::DamageSourceConstraint, target: crate::events::DamageTarget },
DamageToExactTargetMatcher { target: crate::events::DamageTarget },
ManaProducedBySourceMatcher { source_filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] required_provenance: Option<crate::events::mana::ManaProductionProvenance> },
DamageToPlayerMatcher { player_filter: crate::target::PlayerFilter },
PreventableDamageToPlayerMatcher { player_filter: crate::target::PlayerFilter },
DamageToObjectMatcher { filter: crate::target::ObjectFilter },
DamageToPlayerOrObjectMatcher { player_filter: crate::target::PlayerFilter, object_filter: crate::target::ObjectFilter },
CombatDamageMatcher,
PreventableCombatDamageToObjectMatcher { filter: crate::target::ObjectFilter },
PreventableNoncombatDamageToObjectMatcher { filter: crate::target::ObjectFilter },
NoncombatDamageMatcher,
DamageFromSourceMatcher { filter: crate::target::ObjectFilter },
DamageFromSourceToPlayerMatcher { source_filter: crate::target::ObjectFilter, player_filter: crate::target::PlayerFilter },
DamageFromSourceToObjectMatcher { source_filter: crate::target::ObjectFilter, target_filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] combat_only: Option<bool>, preventable_only: bool },
DamageFromSelfMatcher,
DamageToOrFromSelfMatcher,
DamageFromSelfCombatMatcher,
PreventableDamageConstraintMatcher { source: crate::events::damage::matchers::DamageSourceConstraint, target: crate::events::damage::matchers::DamageTargetConstraint },
DamageToSelfMatcher,
DamageToAttachedObjectMatcher,
DamageToSelfConstraintMatcher { #[serde(deserialize_with="deserialize_present_optional")] source_filter: Option<crate::target::ObjectFilter>, #[serde(deserialize_with="deserialize_present_optional")] combat_only: Option<bool> },
DamageToSelfCombatMatcher,
DamageToOtherCreatureYouControlMatcher { noncombat_only: bool },
DamageToSelfFromSourceFilterMatcher { source_filter: crate::target::ObjectFilter, combat_only: bool, source_relation: ironsmith_core::StaticDamageSourceRelation },
WouldCreateTokensUnderControlMatcher { controller_filter: crate::target::PlayerFilter, cause_filter: crate::events::cause::CauseFilter, #[serde(deserialize_with="deserialize_present_optional")] token_filter: Option<crate::target::ObjectFilter> },
WouldPutCountersMatcher { filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] counter_type: Option<crate::object::CounterType>, cause_filter: crate::events::cause::CauseFilter },
WouldRemoveCountersMatcher { filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] counter_type: Option<crate::object::CounterType> },
WouldBecomeTappedMatcher { filter: crate::target::ObjectFilter },
WouldBecomeUntappedMatcher { filter: crate::target::ObjectFilter },
WouldBeDestroyedMatcher { filter: crate::target::ObjectFilter },
ThisWouldBeDestroyedMatcher,
AttachedPermanentWouldBeDestroyedMatcher { aura: crate::ids::ObjectId },
WouldBeSacrificedMatcher { filter: crate::target::ObjectFilter },
RegenerationShieldMatcher { protected: crate::ids::ObjectId },
WouldGainLifeMatcher { player_filter: crate::target::PlayerFilter },
WouldLoseLifeMatcher { player_filter: crate::target::PlayerFilter },
WouldKeywordActionMatcher { action: crate::events::KeywordActionKind, source_filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] performer_filter: Option<crate::target::PlayerFilter> },
WouldLoseGameMatcher,
WouldDrawCardMatcher { player_filter: crate::target::PlayerFilter },
WouldDrawCardWhileLibraryEmptyMatcher { player_filter: crate::target::PlayerFilter },
WouldDrawFirstCardMatcher { player_filter: crate::target::PlayerFilter },
WouldDiscardMatcher { player_filter: crate::target::PlayerFilter, cause_filter: crate::events::cause::CauseFilter, #[serde(deserialize_with="deserialize_present_optional")] card_filter: Option<crate::target::ObjectFilter>, #[serde(deserialize_with="deserialize_present_optional")] destination: Option<crate::zone::Zone> },
WouldEnterBattlefieldMatcher { filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] stable_id: Option<crate::ids::StableId> },
ThisWouldEnterBattlefieldMatcher,
WouldDieMatcher { filter: crate::target::ObjectFilter },
WouldDieDamagedBySourceThisTurnMatcher { filter: crate::target::ObjectFilter, damaged_by: ironsmith_core::DamagedBySource, #[serde(deserialize_with="deserialize_present_optional")] victims: Option<Vec<crate::ids::StableId>> },
WouldDieDamagedByFilteredSourceThisTurnMatcher { victim_filter: crate::target::ObjectFilter, damager_filter: crate::target::ObjectFilter },
ThisWouldDieMatcher,
WouldGoToGraveyardMatcher { filter: crate::target::ObjectFilter },
WouldChangeZoneMatcher { filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] from_zone: Option<crate::zone::Zone>, #[serde(deserialize_with="deserialize_present_optional")] to_zone: Option<crate::zone::Zone>, #[serde(deserialize_with="deserialize_present_optional")] cause_filter: Option<crate::events::cause::CauseFilter>, require_cause_source_match: bool, frozen_tagged_objects: Vec<(crate::tag::TagKey, Vec<S>)> },
WouldBeExiledMatcher { filter: crate::target::ObjectFilter },
ThisWouldGoToGraveyardMatcher,
WouldGoToHandMatcher { player_filter: crate::target::PlayerFilter },
WouldLeaveBattlefieldMatcher { filter: crate::target::ObjectFilter },
ThisWouldEnterTappedUnlessControlTwoOrMoreOtherLandsMatcher,
ThisWouldEnterTappedUnlessControlTwoOrFewerOtherLandsMatcher,
ThisWouldEnterTappedUnlessControlTwoOrMoreBasicLandsMatcher,
ThisWouldEnterTappedUnlessAPlayerHas13OrLessLifeMatcher,
ThisWouldEnterTappedUnlessTwoOrMoreOpponentsMatcher,
ThisWouldEnterTappedUnlessConditionMatcher { condition: crate::effect::Condition, display: String },
ThisWouldEnterWithBloodthirstMatcher,
ThisWouldEnterWithCountersIfConditionMatcher { condition: crate::effect::Condition, condition_display: String },
PreventableCombatDamageToOrByObjectMatcher { to: Box<RetainedReplacementMatcher<S>>, by: Box<RetainedReplacementMatcher<S>> },
PreventableAnyDamageToObjectMatcher { combat: Box<RetainedReplacementMatcher<S>>, noncombat: Box<RetainedReplacementMatcher<S>> },
ConditionalWouldEnterBattlefieldMatcher { enter_matcher: Box<RetainedReplacementMatcher<S>>, #[serde(deserialize_with="deserialize_present_optional")] condition: Option<crate::ConditionExpr> },
ChosenTypeDamageSourceMatcher { ability_source: crate::ids::ObjectId },
DamageAmountReplacementMatcher { source_filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] target_player_filter: Option<crate::target::PlayerFilter>, #[serde(deserialize_with="deserialize_present_optional")] target_object_filter: Option<crate::target::ObjectFilter>, #[serde(deserialize_with="deserialize_present_optional")] condition: Option<crate::ConditionExpr>, combat_only: bool, noncombat_only: bool, #[serde(deserialize_with="deserialize_present_optional")] amount_less_than: Option<crate::effect::Value> },
WouldPutCountersOrEnterWithCountersMatcher { ability_source: crate::ids::ObjectId, controller: crate::ids::PlayerId, filter: crate::target::ObjectFilter, #[serde(deserialize_with="deserialize_present_optional")] player_filter: Option<crate::target::PlayerFilter>, #[serde(deserialize_with="deserialize_present_optional")] counter_type: Option<crate::object::CounterType>, #[serde(deserialize_with="deserialize_present_optional")] actor: Option<crate::target::PlayerFilter>, includes_permanents: bool, effect_only: bool },
DredgeDrawMatcher { amount: u32 },
ConditionalWouldDrawCardMatcher { condition: crate::effect::Condition, display: String },
WouldDrawInstructionMatcher { #[serde(deserialize_with="deserialize_present_optional")] condition: Option<crate::effect::Condition>, except_first_of_draw_step: bool, per_instruction: bool, display: String },
WouldDrawByPlayerMatcher { drawer: crate::target::PlayerFilter, except_first_of_draw_step: bool, display: String },
WouldGoToGraveyardFromAnywhereMatcher { filter: crate::target::ObjectFilter, exclude_cycled: bool },
WouldEnterFromZoneMatcher { enter_matcher: Box<RetainedReplacementMatcher<S>>, not_cast: bool },
TappedForMinimumManaMatcher { inner: Box<RetainedReplacementMatcher<S>>, minimum_amount: u32 },
ConditionalWouldChangeLifeMatcher { player: crate::target::PlayerFilter, loss: bool, #[serde(deserialize_with="deserialize_present_optional")] condition: Option<crate::effect::Condition>, display: String },
}
fn deserialize_present_optional<'de,T:serde::Deserialize<'de>,D:serde::Deserializer<'de>>(value:D)->Result<Option<T>,D::Error>{ <Option<T> as serde::Deserialize>::deserialize(value) }
pub fn retain_replacement_matcher<S,E>(model:NativeReplacementMatcherDescriptor,mut snapshot:impl FnMut(crate::snapshot::ObjectSnapshot)->Result<S,E>,mut error:impl FnMut(String)->E)->Result<RetainedReplacementMatcher<S>,E>{retain_with(model,&mut snapshot,&mut error)}
fn retain_with<S,E>(model:NativeReplacementMatcherDescriptor,snapshot:&mut impl FnMut(crate::snapshot::ObjectSnapshot)->Result<S,E>,error:&mut impl FnMut(String)->E)->Result<RetainedReplacementMatcher<S>,E>{
    let predicate=match model {
Native::DamageToSpecificTargetMatcher { target } => RetainedReplacementMatcherPredicate::DamageToSpecificTargetMatcher { target: target },
Native::DamageSourceToSpecificTargetMatcher { source, target } => RetainedReplacementMatcherPredicate::DamageSourceToSpecificTargetMatcher { source: source, target: target },
Native::DamageToExactTargetMatcher { target } => RetainedReplacementMatcherPredicate::DamageToExactTargetMatcher { target: target },
Native::ManaProducedBySourceMatcher { source_filter, required_provenance } => RetainedReplacementMatcherPredicate::ManaProducedBySourceMatcher { source_filter: source_filter, required_provenance: required_provenance },
Native::DamageToPlayerMatcher { player_filter } => RetainedReplacementMatcherPredicate::DamageToPlayerMatcher { player_filter: player_filter },
Native::PreventableDamageToPlayerMatcher { player_filter } => RetainedReplacementMatcherPredicate::PreventableDamageToPlayerMatcher { player_filter: player_filter },
Native::DamageToObjectMatcher { filter } => RetainedReplacementMatcherPredicate::DamageToObjectMatcher { filter: filter },
Native::DamageToPlayerOrObjectMatcher { player_filter, object_filter } => RetainedReplacementMatcherPredicate::DamageToPlayerOrObjectMatcher { player_filter: player_filter, object_filter: object_filter },
Native::CombatDamageMatcher => RetainedReplacementMatcherPredicate::CombatDamageMatcher,
Native::PreventableCombatDamageToObjectMatcher { filter } => RetainedReplacementMatcherPredicate::PreventableCombatDamageToObjectMatcher { filter: filter },
Native::PreventableNoncombatDamageToObjectMatcher { filter } => RetainedReplacementMatcherPredicate::PreventableNoncombatDamageToObjectMatcher { filter: filter },
Native::NoncombatDamageMatcher => RetainedReplacementMatcherPredicate::NoncombatDamageMatcher,
Native::DamageFromSourceMatcher { filter } => RetainedReplacementMatcherPredicate::DamageFromSourceMatcher { filter: filter },
Native::DamageFromSourceToPlayerMatcher { source_filter, player_filter } => RetainedReplacementMatcherPredicate::DamageFromSourceToPlayerMatcher { source_filter: source_filter, player_filter: player_filter },
Native::DamageFromSourceToObjectMatcher { source_filter, target_filter, combat_only, preventable_only } => RetainedReplacementMatcherPredicate::DamageFromSourceToObjectMatcher { source_filter: source_filter, target_filter: target_filter, combat_only: combat_only, preventable_only: preventable_only },
Native::DamageFromSelfMatcher => RetainedReplacementMatcherPredicate::DamageFromSelfMatcher,
Native::DamageToOrFromSelfMatcher => RetainedReplacementMatcherPredicate::DamageToOrFromSelfMatcher,
Native::DamageFromSelfCombatMatcher => RetainedReplacementMatcherPredicate::DamageFromSelfCombatMatcher,
Native::PreventableDamageConstraintMatcher { source, target } => RetainedReplacementMatcherPredicate::PreventableDamageConstraintMatcher { source: source, target: target },
Native::DamageToSelfMatcher => RetainedReplacementMatcherPredicate::DamageToSelfMatcher,
Native::DamageToAttachedObjectMatcher => RetainedReplacementMatcherPredicate::DamageToAttachedObjectMatcher,
Native::DamageToSelfConstraintMatcher { source_filter, combat_only } => RetainedReplacementMatcherPredicate::DamageToSelfConstraintMatcher { source_filter: source_filter, combat_only: combat_only },
Native::DamageToSelfCombatMatcher => RetainedReplacementMatcherPredicate::DamageToSelfCombatMatcher,
Native::DamageToOtherCreatureYouControlMatcher { noncombat_only } => RetainedReplacementMatcherPredicate::DamageToOtherCreatureYouControlMatcher { noncombat_only: noncombat_only },
Native::DamageToSelfFromSourceFilterMatcher { source_filter, combat_only, source_relation } => RetainedReplacementMatcherPredicate::DamageToSelfFromSourceFilterMatcher { source_filter: source_filter, combat_only: combat_only, source_relation: source_relation },
Native::WouldCreateTokensUnderControlMatcher { controller_filter, cause_filter, token_filter } => RetainedReplacementMatcherPredicate::WouldCreateTokensUnderControlMatcher { controller_filter: controller_filter, cause_filter: cause_filter, token_filter: token_filter },
Native::WouldPutCountersMatcher { filter, counter_type, cause_filter } => RetainedReplacementMatcherPredicate::WouldPutCountersMatcher { filter: filter, counter_type: counter_type, cause_filter: cause_filter },
Native::WouldRemoveCountersMatcher { filter, counter_type } => RetainedReplacementMatcherPredicate::WouldRemoveCountersMatcher { filter: filter, counter_type: counter_type },
Native::WouldBecomeTappedMatcher { filter } => RetainedReplacementMatcherPredicate::WouldBecomeTappedMatcher { filter: filter },
Native::WouldBecomeUntappedMatcher { filter } => RetainedReplacementMatcherPredicate::WouldBecomeUntappedMatcher { filter: filter },
Native::WouldBeDestroyedMatcher { filter } => RetainedReplacementMatcherPredicate::WouldBeDestroyedMatcher { filter: filter },
Native::ThisWouldBeDestroyedMatcher => RetainedReplacementMatcherPredicate::ThisWouldBeDestroyedMatcher,
Native::AttachedPermanentWouldBeDestroyedMatcher { aura } => RetainedReplacementMatcherPredicate::AttachedPermanentWouldBeDestroyedMatcher { aura: aura },
Native::WouldBeSacrificedMatcher { filter } => RetainedReplacementMatcherPredicate::WouldBeSacrificedMatcher { filter: filter },
Native::RegenerationShieldMatcher { protected } => RetainedReplacementMatcherPredicate::RegenerationShieldMatcher { protected: protected },
Native::WouldGainLifeMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldGainLifeMatcher { player_filter: player_filter },
Native::WouldLoseLifeMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldLoseLifeMatcher { player_filter: player_filter },
Native::WouldKeywordActionMatcher { action, source_filter, performer_filter } => RetainedReplacementMatcherPredicate::WouldKeywordActionMatcher { action: action, source_filter: source_filter, performer_filter: performer_filter },
Native::WouldLoseGameMatcher => RetainedReplacementMatcherPredicate::WouldLoseGameMatcher,
Native::WouldDrawCardMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldDrawCardMatcher { player_filter: player_filter },
Native::WouldDrawCardWhileLibraryEmptyMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldDrawCardWhileLibraryEmptyMatcher { player_filter: player_filter },
Native::WouldDrawFirstCardMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldDrawFirstCardMatcher { player_filter: player_filter },
Native::WouldDiscardMatcher { player_filter, cause_filter, card_filter, destination } => RetainedReplacementMatcherPredicate::WouldDiscardMatcher { player_filter: player_filter, cause_filter: cause_filter, card_filter: card_filter, destination: destination },
Native::WouldEnterBattlefieldMatcher { filter, stable_id } => RetainedReplacementMatcherPredicate::WouldEnterBattlefieldMatcher { filter: filter, stable_id: stable_id },
Native::ThisWouldEnterBattlefieldMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterBattlefieldMatcher,
Native::WouldDieMatcher { filter } => RetainedReplacementMatcherPredicate::WouldDieMatcher { filter: filter },
Native::WouldDieDamagedBySourceThisTurnMatcher { filter, damaged_by, victims } => RetainedReplacementMatcherPredicate::WouldDieDamagedBySourceThisTurnMatcher { filter: filter, damaged_by: damaged_by, victims: victims },
Native::WouldDieDamagedByFilteredSourceThisTurnMatcher { victim_filter, damager_filter } => RetainedReplacementMatcherPredicate::WouldDieDamagedByFilteredSourceThisTurnMatcher { victim_filter: victim_filter, damager_filter: damager_filter },
Native::ThisWouldDieMatcher => RetainedReplacementMatcherPredicate::ThisWouldDieMatcher,
Native::WouldGoToGraveyardMatcher { filter } => RetainedReplacementMatcherPredicate::WouldGoToGraveyardMatcher { filter: filter },
Native::WouldChangeZoneMatcher { filter, from_zone, to_zone, cause_filter, require_cause_source_match, frozen_tagged_objects } => RetainedReplacementMatcherPredicate::WouldChangeZoneMatcher { filter: filter, from_zone: from_zone, to_zone: to_zone, cause_filter: cause_filter, require_cause_source_match: require_cause_source_match, frozen_tagged_objects: { let mut records:Vec<_> = frozen_tagged_objects.into_iter().collect(); records.sort_by(|left,right| left.0.cmp(&right.0)); records.into_iter().map(|(tag, values)| Ok((tag, values.into_iter().map(&mut *snapshot).collect::<Result<Vec<_>, E>>()?))).collect::<Result<Vec<_>, E>>()? } },
Native::WouldBeExiledMatcher { filter } => RetainedReplacementMatcherPredicate::WouldBeExiledMatcher { filter: filter },
Native::ThisWouldGoToGraveyardMatcher => RetainedReplacementMatcherPredicate::ThisWouldGoToGraveyardMatcher,
Native::WouldGoToHandMatcher { player_filter } => RetainedReplacementMatcherPredicate::WouldGoToHandMatcher { player_filter: player_filter },
Native::WouldLeaveBattlefieldMatcher { filter } => RetainedReplacementMatcherPredicate::WouldLeaveBattlefieldMatcher { filter: filter },
Native::ThisWouldEnterTappedUnlessControlTwoOrMoreOtherLandsMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrMoreOtherLandsMatcher,
Native::ThisWouldEnterTappedUnlessControlTwoOrFewerOtherLandsMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrFewerOtherLandsMatcher,
Native::ThisWouldEnterTappedUnlessControlTwoOrMoreBasicLandsMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrMoreBasicLandsMatcher,
Native::ThisWouldEnterTappedUnlessAPlayerHas13OrLessLifeMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessAPlayerHas13OrLessLifeMatcher,
Native::ThisWouldEnterTappedUnlessTwoOrMoreOpponentsMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessTwoOrMoreOpponentsMatcher,
Native::ThisWouldEnterTappedUnlessConditionMatcher { condition, display } => RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessConditionMatcher { condition: condition, display: display },
Native::ThisWouldEnterWithBloodthirstMatcher => RetainedReplacementMatcherPredicate::ThisWouldEnterWithBloodthirstMatcher,
Native::ThisWouldEnterWithCountersIfConditionMatcher { condition, condition_display } => RetainedReplacementMatcherPredicate::ThisWouldEnterWithCountersIfConditionMatcher { condition: condition, condition_display: condition_display },
Native::PreventableCombatDamageToOrByObjectMatcher { to, by } => RetainedReplacementMatcherPredicate::PreventableCombatDamageToOrByObjectMatcher { to: Box::new(retain_with(to.export_descriptor().map_err(&mut *error)?, snapshot, error)?), by: Box::new(retain_with(by.export_descriptor().map_err(&mut *error)?, snapshot, error)?) },
Native::PreventableAnyDamageToObjectMatcher { combat, noncombat } => RetainedReplacementMatcherPredicate::PreventableAnyDamageToObjectMatcher { combat: Box::new(retain_with(combat.export_descriptor().map_err(&mut *error)?, snapshot, error)?), noncombat: Box::new(retain_with(noncombat.export_descriptor().map_err(&mut *error)?, snapshot, error)?) },
Native::ConditionalWouldEnterBattlefieldMatcher { enter_matcher, condition } => RetainedReplacementMatcherPredicate::ConditionalWouldEnterBattlefieldMatcher { enter_matcher: Box::new(retain_with(enter_matcher.export_descriptor().map_err(&mut *error)?, snapshot, error)?), condition: condition },
Native::ChosenTypeDamageSourceMatcher { ability_source } => RetainedReplacementMatcherPredicate::ChosenTypeDamageSourceMatcher { ability_source: ability_source },
Native::DamageAmountReplacementMatcher { source_filter, target_player_filter, target_object_filter, condition, combat_only, noncombat_only, amount_less_than } => RetainedReplacementMatcherPredicate::DamageAmountReplacementMatcher { source_filter: source_filter, target_player_filter: target_player_filter, target_object_filter: target_object_filter, condition: condition, combat_only: combat_only, noncombat_only: noncombat_only, amount_less_than: amount_less_than },
Native::WouldPutCountersOrEnterWithCountersMatcher { ability_source, controller, filter, player_filter, counter_type, actor, includes_permanents, effect_only } => RetainedReplacementMatcherPredicate::WouldPutCountersOrEnterWithCountersMatcher { ability_source: ability_source, controller: controller, filter: filter, player_filter: player_filter, counter_type: counter_type, actor: actor, includes_permanents: includes_permanents, effect_only: effect_only },
Native::DredgeDrawMatcher { amount } => RetainedReplacementMatcherPredicate::DredgeDrawMatcher { amount: amount },
Native::ConditionalWouldDrawCardMatcher { condition, display } => RetainedReplacementMatcherPredicate::ConditionalWouldDrawCardMatcher { condition: condition, display: display },
Native::WouldDrawInstructionMatcher { condition, except_first_of_draw_step, per_instruction, display } => RetainedReplacementMatcherPredicate::WouldDrawInstructionMatcher { condition: condition, except_first_of_draw_step: except_first_of_draw_step, per_instruction: per_instruction, display: display },
Native::WouldDrawByPlayerMatcher { drawer, except_first_of_draw_step, display } => RetainedReplacementMatcherPredicate::WouldDrawByPlayerMatcher { drawer: drawer, except_first_of_draw_step: except_first_of_draw_step, display: display },
Native::WouldGoToGraveyardFromAnywhereMatcher { filter, exclude_cycled } => RetainedReplacementMatcherPredicate::WouldGoToGraveyardFromAnywhereMatcher { filter: filter, exclude_cycled: exclude_cycled },
Native::WouldEnterFromZoneMatcher { enter_matcher, not_cast } => RetainedReplacementMatcherPredicate::WouldEnterFromZoneMatcher { enter_matcher: Box::new(retain_with(enter_matcher.export_descriptor().map_err(&mut *error)?, snapshot, error)?), not_cast: not_cast },
Native::TappedForMinimumManaMatcher { inner, minimum_amount } => RetainedReplacementMatcherPredicate::TappedForMinimumManaMatcher { inner: Box::new(retain_with(inner.export_descriptor().map_err(&mut *error)?, snapshot, error)?), minimum_amount: minimum_amount },
Native::ConditionalWouldChangeLifeMatcher { player, loss, condition, display } => RetainedReplacementMatcherPredicate::ConditionalWouldChangeLifeMatcher { player: player, loss: loss, condition: condition, display: display },
    };
    Ok(RetainedReplacementMatcher{version:REPLACEMENT_MATCHER_CODEC_VERSION,predicate})
}
impl<S> RetainedReplacementMatcher<S> {
    pub fn restore<E>(self,mut snapshot:impl FnMut(S)->Result<crate::snapshot::ObjectSnapshot,E>,mut error:impl FnMut(String)->E)->Result<NativeReplacementMatcherDescriptor,E>{self.validate_tree(&mut error)?;self.restore_with(&mut snapshot,&mut error,0)}
    fn validate_tree<E>(&self,error:&mut impl FnMut(String)->E)->Result<(),E>{
        let mut pending=vec![(self,0usize)];
        while let Some((value,depth))=pending.pop(){
            if depth>=64 {return Err(error("replacement predicate nesting limit exceeded".into()));}
            if value.version!=REPLACEMENT_MATCHER_CODEC_VERSION {return Err(error("unsupported replacement predicate codec version".into()));}
            match &value.predicate {
                RetainedReplacementMatcherPredicate::PreventableCombatDamageToOrByObjectMatcher{to,by}=>{pending.push((to,depth+1));pending.push((by,depth+1));},
                RetainedReplacementMatcherPredicate::PreventableAnyDamageToObjectMatcher{combat,noncombat}=>{pending.push((combat,depth+1));pending.push((noncombat,depth+1));},
                RetainedReplacementMatcherPredicate::ConditionalWouldEnterBattlefieldMatcher{enter_matcher,..} | RetainedReplacementMatcherPredicate::WouldEnterFromZoneMatcher{enter_matcher,..} => pending.push((enter_matcher,depth+1)),
                RetainedReplacementMatcherPredicate::TappedForMinimumManaMatcher{inner,..}=>pending.push((inner,depth+1)),
                _=>{},
            }
        }
        Ok(())
    }
    fn restore_with<E>(self,snapshot:&mut impl FnMut(S)->Result<crate::snapshot::ObjectSnapshot,E>,error:&mut impl FnMut(String)->E,depth:usize)->Result<NativeReplacementMatcherDescriptor,E>{
        if self.version!=REPLACEMENT_MATCHER_CODEC_VERSION {return Err(error("unsupported replacement predicate codec version".into()));}
        if depth>=64 {return Err(error("replacement predicate nesting limit exceeded".into()));}
        Ok(match self.predicate {
RetainedReplacementMatcherPredicate::DamageToSpecificTargetMatcher { target } => Native::DamageToSpecificTargetMatcher { target: target },
RetainedReplacementMatcherPredicate::DamageSourceToSpecificTargetMatcher { source, target } => Native::DamageSourceToSpecificTargetMatcher { source: source, target: target },
RetainedReplacementMatcherPredicate::DamageToExactTargetMatcher { target } => Native::DamageToExactTargetMatcher { target: target },
RetainedReplacementMatcherPredicate::ManaProducedBySourceMatcher { source_filter, required_provenance } => Native::ManaProducedBySourceMatcher { source_filter: source_filter, required_provenance: required_provenance },
RetainedReplacementMatcherPredicate::DamageToPlayerMatcher { player_filter } => Native::DamageToPlayerMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::PreventableDamageToPlayerMatcher { player_filter } => Native::PreventableDamageToPlayerMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::DamageToObjectMatcher { filter } => Native::DamageToObjectMatcher { filter: filter },
RetainedReplacementMatcherPredicate::DamageToPlayerOrObjectMatcher { player_filter, object_filter } => Native::DamageToPlayerOrObjectMatcher { player_filter: player_filter, object_filter: object_filter },
RetainedReplacementMatcherPredicate::CombatDamageMatcher => Native::CombatDamageMatcher,
RetainedReplacementMatcherPredicate::PreventableCombatDamageToObjectMatcher { filter } => Native::PreventableCombatDamageToObjectMatcher { filter: filter },
RetainedReplacementMatcherPredicate::PreventableNoncombatDamageToObjectMatcher { filter } => Native::PreventableNoncombatDamageToObjectMatcher { filter: filter },
RetainedReplacementMatcherPredicate::NoncombatDamageMatcher => Native::NoncombatDamageMatcher,
RetainedReplacementMatcherPredicate::DamageFromSourceMatcher { filter } => Native::DamageFromSourceMatcher { filter: filter },
RetainedReplacementMatcherPredicate::DamageFromSourceToPlayerMatcher { source_filter, player_filter } => Native::DamageFromSourceToPlayerMatcher { source_filter: source_filter, player_filter: player_filter },
RetainedReplacementMatcherPredicate::DamageFromSourceToObjectMatcher { source_filter, target_filter, combat_only, preventable_only } => Native::DamageFromSourceToObjectMatcher { source_filter: source_filter, target_filter: target_filter, combat_only: combat_only, preventable_only: preventable_only },
RetainedReplacementMatcherPredicate::DamageFromSelfMatcher => Native::DamageFromSelfMatcher,
RetainedReplacementMatcherPredicate::DamageToOrFromSelfMatcher => Native::DamageToOrFromSelfMatcher,
RetainedReplacementMatcherPredicate::DamageFromSelfCombatMatcher => Native::DamageFromSelfCombatMatcher,
RetainedReplacementMatcherPredicate::PreventableDamageConstraintMatcher { source, target } => Native::PreventableDamageConstraintMatcher { source: source, target: target },
RetainedReplacementMatcherPredicate::DamageToSelfMatcher => Native::DamageToSelfMatcher,
RetainedReplacementMatcherPredicate::DamageToAttachedObjectMatcher => Native::DamageToAttachedObjectMatcher,
RetainedReplacementMatcherPredicate::DamageToSelfConstraintMatcher { source_filter, combat_only } => Native::DamageToSelfConstraintMatcher { source_filter: source_filter, combat_only: combat_only },
RetainedReplacementMatcherPredicate::DamageToSelfCombatMatcher => Native::DamageToSelfCombatMatcher,
RetainedReplacementMatcherPredicate::DamageToOtherCreatureYouControlMatcher { noncombat_only } => Native::DamageToOtherCreatureYouControlMatcher { noncombat_only: noncombat_only },
RetainedReplacementMatcherPredicate::DamageToSelfFromSourceFilterMatcher { source_filter, combat_only, source_relation } => Native::DamageToSelfFromSourceFilterMatcher { source_filter: source_filter, combat_only: combat_only, source_relation: source_relation },
RetainedReplacementMatcherPredicate::WouldCreateTokensUnderControlMatcher { controller_filter, cause_filter, token_filter } => Native::WouldCreateTokensUnderControlMatcher { controller_filter: controller_filter, cause_filter: cause_filter, token_filter: token_filter },
RetainedReplacementMatcherPredicate::WouldPutCountersMatcher { filter, counter_type, cause_filter } => Native::WouldPutCountersMatcher { filter: filter, counter_type: counter_type, cause_filter: cause_filter },
RetainedReplacementMatcherPredicate::WouldRemoveCountersMatcher { filter, counter_type } => Native::WouldRemoveCountersMatcher { filter: filter, counter_type: counter_type },
RetainedReplacementMatcherPredicate::WouldBecomeTappedMatcher { filter } => Native::WouldBecomeTappedMatcher { filter: filter },
RetainedReplacementMatcherPredicate::WouldBecomeUntappedMatcher { filter } => Native::WouldBecomeUntappedMatcher { filter: filter },
RetainedReplacementMatcherPredicate::WouldBeDestroyedMatcher { filter } => Native::WouldBeDestroyedMatcher { filter: filter },
RetainedReplacementMatcherPredicate::ThisWouldBeDestroyedMatcher => Native::ThisWouldBeDestroyedMatcher,
RetainedReplacementMatcherPredicate::AttachedPermanentWouldBeDestroyedMatcher { aura } => Native::AttachedPermanentWouldBeDestroyedMatcher { aura: aura },
RetainedReplacementMatcherPredicate::WouldBeSacrificedMatcher { filter } => Native::WouldBeSacrificedMatcher { filter: filter },
RetainedReplacementMatcherPredicate::RegenerationShieldMatcher { protected } => Native::RegenerationShieldMatcher { protected: protected },
RetainedReplacementMatcherPredicate::WouldGainLifeMatcher { player_filter } => Native::WouldGainLifeMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldLoseLifeMatcher { player_filter } => Native::WouldLoseLifeMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldKeywordActionMatcher { action, source_filter, performer_filter } => Native::WouldKeywordActionMatcher { action: action, source_filter: source_filter, performer_filter: performer_filter },
RetainedReplacementMatcherPredicate::WouldLoseGameMatcher => Native::WouldLoseGameMatcher,
RetainedReplacementMatcherPredicate::WouldDrawCardMatcher { player_filter } => Native::WouldDrawCardMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldDrawCardWhileLibraryEmptyMatcher { player_filter } => Native::WouldDrawCardWhileLibraryEmptyMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldDrawFirstCardMatcher { player_filter } => Native::WouldDrawFirstCardMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldDiscardMatcher { player_filter, cause_filter, card_filter, destination } => Native::WouldDiscardMatcher { player_filter: player_filter, cause_filter: cause_filter, card_filter: card_filter, destination: destination },
RetainedReplacementMatcherPredicate::WouldEnterBattlefieldMatcher { filter, stable_id } => Native::WouldEnterBattlefieldMatcher { filter: filter, stable_id: stable_id },
RetainedReplacementMatcherPredicate::ThisWouldEnterBattlefieldMatcher => Native::ThisWouldEnterBattlefieldMatcher,
RetainedReplacementMatcherPredicate::WouldDieMatcher { filter } => Native::WouldDieMatcher { filter: filter },
RetainedReplacementMatcherPredicate::WouldDieDamagedBySourceThisTurnMatcher { filter, damaged_by, victims } => Native::WouldDieDamagedBySourceThisTurnMatcher { filter: filter, damaged_by: damaged_by, victims: victims },
RetainedReplacementMatcherPredicate::WouldDieDamagedByFilteredSourceThisTurnMatcher { victim_filter, damager_filter } => Native::WouldDieDamagedByFilteredSourceThisTurnMatcher { victim_filter: victim_filter, damager_filter: damager_filter },
RetainedReplacementMatcherPredicate::ThisWouldDieMatcher => Native::ThisWouldDieMatcher,
RetainedReplacementMatcherPredicate::WouldGoToGraveyardMatcher { filter } => Native::WouldGoToGraveyardMatcher { filter: filter },
RetainedReplacementMatcherPredicate::WouldChangeZoneMatcher { filter, from_zone, to_zone, cause_filter, require_cause_source_match, frozen_tagged_objects } => Native::WouldChangeZoneMatcher { filter: filter, from_zone: from_zone, to_zone: to_zone, cause_filter: cause_filter, require_cause_source_match: require_cause_source_match, frozen_tagged_objects: { if frozen_tagged_objects.windows(2).any(|pair| pair[0].0 >= pair[1].0) { return Err(error("captured predicate tags must be ordered and unique".into())); } frozen_tagged_objects.into_iter().map(|(tag, values)| Ok((tag,values.into_iter().map(&mut *snapshot).collect::<Result<Vec<_>, E>>()?))).collect::<Result<_,E>>()? } },
RetainedReplacementMatcherPredicate::WouldBeExiledMatcher { filter } => Native::WouldBeExiledMatcher { filter: filter },
RetainedReplacementMatcherPredicate::ThisWouldGoToGraveyardMatcher => Native::ThisWouldGoToGraveyardMatcher,
RetainedReplacementMatcherPredicate::WouldGoToHandMatcher { player_filter } => Native::WouldGoToHandMatcher { player_filter: player_filter },
RetainedReplacementMatcherPredicate::WouldLeaveBattlefieldMatcher { filter } => Native::WouldLeaveBattlefieldMatcher { filter: filter },
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrMoreOtherLandsMatcher => Native::ThisWouldEnterTappedUnlessControlTwoOrMoreOtherLandsMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrFewerOtherLandsMatcher => Native::ThisWouldEnterTappedUnlessControlTwoOrFewerOtherLandsMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessControlTwoOrMoreBasicLandsMatcher => Native::ThisWouldEnterTappedUnlessControlTwoOrMoreBasicLandsMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessAPlayerHas13OrLessLifeMatcher => Native::ThisWouldEnterTappedUnlessAPlayerHas13OrLessLifeMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessTwoOrMoreOpponentsMatcher => Native::ThisWouldEnterTappedUnlessTwoOrMoreOpponentsMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterTappedUnlessConditionMatcher { condition, display } => Native::ThisWouldEnterTappedUnlessConditionMatcher { condition: condition, display: display },
RetainedReplacementMatcherPredicate::ThisWouldEnterWithBloodthirstMatcher => Native::ThisWouldEnterWithBloodthirstMatcher,
RetainedReplacementMatcherPredicate::ThisWouldEnterWithCountersIfConditionMatcher { condition, condition_display } => Native::ThisWouldEnterWithCountersIfConditionMatcher { condition: condition, condition_display: condition_display },
RetainedReplacementMatcherPredicate::PreventableCombatDamageToOrByObjectMatcher { to, by } => Native::PreventableCombatDamageToOrByObjectMatcher { to: { if !matches!(&to.predicate,RetainedReplacementMatcherPredicate::PreventableCombatDamageToObjectMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = to.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::damage::matchers::PreventableCombatDamageToObjectMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? }, by: { if !matches!(&by.predicate,RetainedReplacementMatcherPredicate::DamageFromSourceMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = by.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::damage::matchers::DamageFromSourceMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? } },
RetainedReplacementMatcherPredicate::PreventableAnyDamageToObjectMatcher { combat, noncombat } => Native::PreventableAnyDamageToObjectMatcher { combat: { if !matches!(&combat.predicate,RetainedReplacementMatcherPredicate::PreventableCombatDamageToObjectMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = combat.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::damage::matchers::PreventableCombatDamageToObjectMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? }, noncombat: { if !matches!(&noncombat.predicate,RetainedReplacementMatcherPredicate::PreventableNoncombatDamageToObjectMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = noncombat.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::damage::matchers::PreventableNoncombatDamageToObjectMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? } },
RetainedReplacementMatcherPredicate::ConditionalWouldEnterBattlefieldMatcher { enter_matcher, condition } => Native::ConditionalWouldEnterBattlefieldMatcher { enter_matcher: { if !matches!(&enter_matcher.predicate,RetainedReplacementMatcherPredicate::WouldEnterBattlefieldMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = enter_matcher.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::zones::matchers::WouldEnterBattlefieldMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? }, condition: condition },
RetainedReplacementMatcherPredicate::ChosenTypeDamageSourceMatcher { ability_source } => Native::ChosenTypeDamageSourceMatcher { ability_source: ability_source },
RetainedReplacementMatcherPredicate::DamageAmountReplacementMatcher { source_filter, target_player_filter, target_object_filter, condition, combat_only, noncombat_only, amount_less_than } => Native::DamageAmountReplacementMatcher { source_filter: source_filter, target_player_filter: target_player_filter, target_object_filter: target_object_filter, condition: condition, combat_only: combat_only, noncombat_only: noncombat_only, amount_less_than: amount_less_than },
RetainedReplacementMatcherPredicate::WouldPutCountersOrEnterWithCountersMatcher { ability_source, controller, filter, player_filter, counter_type, actor, includes_permanents, effect_only } => Native::WouldPutCountersOrEnterWithCountersMatcher { ability_source: ability_source, controller: controller, filter: filter, player_filter: player_filter, counter_type: counter_type, actor: actor, includes_permanents: includes_permanents, effect_only: effect_only },
RetainedReplacementMatcherPredicate::DredgeDrawMatcher { amount } => Native::DredgeDrawMatcher { amount: amount },
RetainedReplacementMatcherPredicate::ConditionalWouldDrawCardMatcher { condition, display } => Native::ConditionalWouldDrawCardMatcher { condition: condition, display: display },
RetainedReplacementMatcherPredicate::WouldDrawInstructionMatcher { condition, except_first_of_draw_step, per_instruction, display } => Native::WouldDrawInstructionMatcher { condition: condition, except_first_of_draw_step: except_first_of_draw_step, per_instruction: per_instruction, display: display },
RetainedReplacementMatcherPredicate::WouldDrawByPlayerMatcher { drawer, except_first_of_draw_step, display } => Native::WouldDrawByPlayerMatcher { drawer: drawer, except_first_of_draw_step: except_first_of_draw_step, display: display },
RetainedReplacementMatcherPredicate::WouldGoToGraveyardFromAnywhereMatcher { filter, exclude_cycled } => Native::WouldGoToGraveyardFromAnywhereMatcher { filter: filter, exclude_cycled: exclude_cycled },
RetainedReplacementMatcherPredicate::WouldEnterFromZoneMatcher { enter_matcher, not_cast } => Native::WouldEnterFromZoneMatcher { enter_matcher: { if !matches!(&enter_matcher.predicate,RetainedReplacementMatcherPredicate::WouldEnterBattlefieldMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = enter_matcher.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::zones::matchers::WouldEnterBattlefieldMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? }, not_cast: not_cast },
RetainedReplacementMatcherPredicate::TappedForMinimumManaMatcher { inner, minimum_amount } => Native::TappedForMinimumManaMatcher { inner: { if !matches!(&inner.predicate,RetainedReplacementMatcherPredicate::ManaProducedBySourceMatcher{..}) {return Err(error("nested predicate has the wrong native kind".into()));} let child = inner.restore_with(snapshot, error, depth + 1)?; let child = crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(child).map_err(&mut *error)?; child.downcast_ref::<crate::events::mana::matchers::ManaProducedBySourceMatcher>().cloned().ok_or_else(|| error("nested predicate has the wrong native kind".into()))? }, minimum_amount: minimum_amount },
RetainedReplacementMatcherPredicate::ConditionalWouldChangeLifeMatcher { player, loss, condition, display } => Native::ConditionalWouldChangeLifeMatcher { player: player, loss: loss, condition: condition, display: display },
        })
    }
}

#[cfg(test)]
mod canonical_replacement_matcher_schema_contract_tests {
    use super::*;
    use crate::events::{ReplacementMatcher,LifeGainEvent,EventContext};
    use crate::events::life::matchers::WouldGainLifeMatcher;
    use crate::target::{ObjectFilter,PlayerFilter};
    use crate::ids::PlayerId;
    fn retain(native:NativeReplacementMatcherDescriptor)->RetainedReplacementMatcher<()> {retain_replacement_matcher(native,|_|Err::<(),_>("unexpected snapshot".to_string()),|detail|detail).unwrap()}
    fn restore(value:RetainedReplacementMatcher<()>)->Result<Box<dyn crate::events::ReplacementMatcher>,String>{let native=value.restore(|_|Err("unexpected snapshot".to_string()),|detail|detail)?;crate::replacement_matcher_descriptor::restore_replacement_matcher_descriptor(native)}
    #[test]fn canonical_same_display_predicates_keep_distinct_gameplay_applicability(){let game=crate::tests::test_helpers::setup_two_player_game();let alice=PlayerId::from_index(0);let bob=PlayerId::from_index(1);let ctx=EventContext::for_controller(alice,&game);let event=LifeGainEvent::new(alice,3);for (player,expected) in [(alice,true),(bob,false)]{let native=WouldGainLifeMatcher::new(PlayerFilter::Specific(player));let encoded=retain(native.export_descriptor().unwrap());let json=serde_json::to_string(&encoded).unwrap();let decoded=serde_json::from_str(&json).unwrap();assert_eq!(restore(decoded).unwrap().matches_event(&event,&ctx).unwrap(),expected);}}
    #[test]fn nullable_capture_is_required_and_unknown_fields_versions_reject(){let model=retain(Native::ConditionalWouldChangeLifeMatcher{player:PlayerFilter::You,loss:false,condition:None,display:"Same display".into()});let json=serde_json::to_value(&model).unwrap();let mut missing=json.clone();missing["predicate"]["payload"].as_object_mut().unwrap().remove("condition");assert!(serde_json::from_value::<RetainedReplacementMatcher<()>>(missing).is_err());let mut unknown=json.clone();unknown["predicate"]["payload"]["extra"]=serde_json::json!(true);assert!(serde_json::from_value::<RetainedReplacementMatcher<()>>(unknown).is_err());let mut version=model;version.version=0;assert!(restore(version).unwrap_err().contains("version"));}
    #[test]fn recursive_mana_predicate_preserves_provenance_and_rejects_wrong_child_kind(){let inner=crate::events::mana::matchers::ManaProducedBySourceMatcher::tapped_source_for_mana(ObjectFilter::artifact());let model=retain(Native::TappedForMinimumManaMatcher{inner,minimum_amount:7});let json=serde_json::to_value(&model).unwrap();let decoded=serde_json::from_value(json.clone()).unwrap();let native=restore(decoded).unwrap();let predicate=native.mana_predicate().unwrap();assert_eq!(predicate.minimum_amount,7);assert_eq!(predicate.required_provenance,Some(crate::events::mana::ManaProductionProvenance::TappedSourceForMana));assert!(!native.may_match_event_kind(crate::events::EventKind::LifeGain));let mut malformed=json;malformed["predicate"]["payload"]["inner"]["predicate"]=serde_json::to_value(retain(Native::WouldGainLifeMatcher{player_filter:PlayerFilter::Any}).predicate).unwrap();let decoded=serde_json::from_value(malformed).unwrap();assert!(restore(decoded).unwrap_err().contains("wrong native kind"));}
    #[test]fn recursive_limit_rejects_before_partial_restore(){let mut value=retain(Native::ManaProducedBySourceMatcher{source_filter:ObjectFilter::artifact(),required_provenance:None});for _ in 0..64{value=RetainedReplacementMatcher{version:REPLACEMENT_MATCHER_CODEC_VERSION,predicate:RetainedReplacementMatcherPredicate::TappedForMinimumManaMatcher{inner:Box::new(value),minimum_amount:1}};}assert!(restore(value).unwrap_err().contains("nesting limit"));}
}
