use super::super::lexer::OwnedLexToken;
use super::super::rule_engine::{LexClauseView, LexUnsupportedDiagnoser, LexUnsupportedRuleDef};
use super::dispatch_inner as inner;
use crate::cards::builders::CardTextError;

const SENTENCE_UNSUPPORTED_RULES_LEXED: [LexUnsupportedRuleDef; 30] = [
    LexUnsupportedRuleDef {
        id: "enters-as-copy",
        priority: 20,
        heads: &[],
        shape_mask: 0,
        message: "unsupported enters-as-copy replacement clause",
        predicate: inner::sentence_has_enters_as_copy_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "each-player-lose-discard-sacrifice-chain",
        priority: 100,
        heads: &["each"],
        shape_mask: 0,
        message: "unsupported each-player lose/discard/sacrifice chain clause",
        predicate: inner::sentence_has_each_player_lose_discard_sacrifice_chain_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "each-player-exile-sacrifice-return-this-way",
        priority: 110,
        heads: &["each"],
        shape_mask: 0,
        message: "unsupported each-player exile/sacrifice/return-this-way clause",
        predicate: inner::sentence_has_each_player_exile_sacrifice_return_exiled_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "put-one-into-hand-rest-zone",
        priority: 115,
        heads: &["put", "then"],
        shape_mask: 0,
        message: "unsupported put-into-hand with rest clause",
        predicate: inner::sentence_has_put_one_of_them_into_hand_rest_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "lose-all-abilities-with-becomes",
        priority: 120,
        heads: &["target", "that", "it", "this", "creatures"],
        shape_mask: 0,
        message: "unsupported loses-all-abilities with becomes clause",
        predicate: inner::sentence_has_loses_all_abilities_with_becomes_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "spent-to-cast-conditional",
        priority: 130,
        heads: &["if", "unless", "when", "as"],
        shape_mask: 0,
        message: "unsupported spent-to-cast conditional clause",
        predicate: inner::sentence_has_spent_to_cast_this_spell_without_condition_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "would-enter-instead",
        priority: 140,
        heads: &["if", "that", "it", "this"],
        shape_mask: 0,
        message: "unsupported would-enter replacement clause",
        predicate: inner::sentence_has_would_enter_instead_replacement_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "different-mana-value-constraint",
        priority: 150,
        heads: &[],
        shape_mask: 0,
        message: "unsupported different-mana-value constraint clause",
        predicate: inner::sentence_has_different_mana_value_constraint_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "most-common-color-constraint",
        priority: 160,
        heads: &["choose", "destroy", "exile", "return"],
        shape_mask: 0,
        message: "unsupported most-common-color constraint clause",
        predicate: inner::sentence_has_most_common_color_constraint_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "power-vs-count-constraint",
        priority: 170,
        heads: &["if", "target", "destroy", "exile", "return"],
        shape_mask: 0,
        message: "unsupported power-vs-count conditional clause",
        predicate: inner::sentence_has_power_vs_count_constraint_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "put-into-graveyards-from-battlefield-this-turn",
        priority: 180,
        heads: &["for", "choose", "target", "destroy"],
        shape_mask: 0,
        message: "unsupported put-into-graveyards-from-battlefield count clause",
        predicate: inner::sentence_has_put_into_graveyards_from_battlefield_this_turn_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "phase-out-until-leaves",
        priority: 190,
        heads: &["phase", "target", "it", "that"],
        shape_mask: 0,
        message: "unsupported phase-out-until-leaves clause",
        predicate: inner::sentence_has_phase_out_until_leaves_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "same-name-as-another-in-hand",
        priority: 200,
        heads: &["target", "choose", "discard"],
        shape_mask: 0,
        message: "unsupported same-name-as-another-in-hand discard clause",
        predicate: inner::sentence_has_same_name_as_another_in_hand_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "for-each-mana-from-spent",
        priority: 210,
        heads: &["for"],
        shape_mask: 0,
        message: "unsupported for-each-mana-from-spent clause",
        predicate: inner::sentence_has_for_each_mana_from_spent_to_cast_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "when-you-sacrifice-this-way",
        priority: 230,
        heads: &["when"],
        shape_mask: 0,
        message: "unsupported when-you-sacrifice-this-way clause",
        predicate: inner::sentence_has_when_you_sacrifice_this_way_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "sacrifice-any-number-then-draw-that-many",
        priority: 240,
        heads: &["sacrifice", "each", "target", "you"],
        shape_mask: 0,
        message: "unsupported sacrifice-any-number-then-draw-that-many clause",
        predicate: inner::sentence_has_sacrifice_any_number_then_draw_that_many_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "greatest-mana-value",
        priority: 250,
        heads: &["choose", "destroy", "exile", "return"],
        shape_mask: 0,
        message: "unsupported greatest-mana-value selection clause",
        predicate: inner::sentence_has_greatest_mana_value_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "least-power-among-creatures",
        priority: 260,
        heads: &["choose", "destroy", "exile", "return"],
        shape_mask: 0,
        message: "unsupported least-power-among-creatures selection clause",
        predicate: inner::sentence_has_least_power_among_creatures_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "villainous-choice",
        priority: 270,
        heads: &["villainous"],
        shape_mask: 0,
        message: "unsupported villainous-choice clause",
        predicate: inner::sentence_has_villainous_choice_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "divided-evenly",
        priority: 280,
        heads: &["divide", "deals", "deal", "distribute"],
        shape_mask: 0,
        message: "unsupported divided-evenly damage clause",
        predicate: inner::sentence_has_divided_evenly_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "different-names",
        priority: 290,
        heads: &["choose", "target", "destroy", "exile"],
        shape_mask: 0,
        message: "unsupported different-names selection clause",
        predicate: inner::sentence_has_different_names_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "chosen-at-random",
        priority: 300,
        heads: &["choose", "target", "discard", "exile"],
        shape_mask: 0,
        message: "unsupported chosen-at-random clause",
        predicate: inner::sentence_has_chosen_at_random_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "defending-players-choice",
        priority: 320,
        heads: &["defending", "target", "of"],
        shape_mask: 0,
        message: "unsupported defending-players-choice clause",
        predicate: inner::sentence_has_defending_players_choice_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "creature-token-player-planeswalker-target",
        priority: 330,
        heads: &["target"],
        shape_mask: 0,
        message: "unsupported creature-token/player/planeswalker target clause",
        predicate: inner::sentence_has_target_creature_token_player_planeswalker_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "if-you-sacrifice-an-island-this-way",
        priority: 340,
        heads: &["if"],
        shape_mask: 0,
        message: "unsupported if-you-sacrifice-an-island-this-way clause",
        predicate: inner::sentence_has_if_you_sacrifice_an_island_this_way_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "spent-to-cast-condition",
        priority: 350,
        heads: &["if", "unless", "when", "as"],
        shape_mask: 0,
        message: "unsupported spent-to-cast condition clause",
        predicate: inner::sentence_has_spent_to_cast_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "face-down",
        priority: 360,
        heads: &["face", "turn", "cast", "exile", "manifest"],
        shape_mask: 0,
        message: "unsupported face-down clause",
        predicate: inner::sentence_has_face_down_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "copy-spell-legendary-exception",
        priority: 370,
        heads: &["copy"],
        shape_mask: 0,
        message: "unsupported copy-spell legendary-exception clause",
        predicate: inner::sentence_has_copy_spell_legendary_exception_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "return-each-creature-that-isnt-list",
        priority: 380,
        heads: &["return"],
        shape_mask: 0,
        message: "unsupported return-each-creature-that-isnt-list clause",
        predicate: inner::sentence_has_return_each_creature_that_isnt_list_clause_rule_lexed,
    },
    LexUnsupportedRuleDef {
        id: "negated-untap",
        priority: 390,
        heads: &["this", "that", "target", "it", "creatures", "players"],
        shape_mask: 0,
        message: "unsupported negated untap clause",
        predicate: inner::sentence_has_unsupported_negated_untap_clause_rule_lexed,
    },
];

const SENTENCE_UNSUPPORTED_DIAGNOSER_LEXED: LexUnsupportedDiagnoser =
    LexUnsupportedDiagnoser::new(&SENTENCE_UNSUPPORTED_RULES_LEXED);

pub(super) fn diagnose_sentence_unsupported_lexed(
    tokens: &[OwnedLexToken],
) -> Option<CardTextError> {
    if inner::sentence_looks_like_supported_negated_untap_clause(tokens) {
        return None;
    }
    let view = LexClauseView::from_tokens(tokens);
    SENTENCE_UNSUPPORTED_DIAGNOSER_LEXED.diagnose(&view, "clause")
}
