// @generated by the explicit catalog data-maintenance job; runtime-owned.
// Do not edit manually.
pub const GENERATED_MELD_COUNTERPARTS: &[(&str, &str)] = &[
    ("Argoth, Sanctum of Nature", "Titania, Voice of Gaea"),
    ("Bruna, the Fading Light", "Gisela, the Broken Blade"),
    ("Fang, Fearless l'Cie", "Vanille, Cheerful l'Cie"),
    ("Gisela, the Broken Blade", "Bruna, the Fading Light"),
    ("Graf Rats", "Midnight Scavengers"),
    ("Hanweir Battlements", "Hanweir Garrison"),
    ("Hanweir Garrison", "Hanweir Battlements"),
    ("Midnight Scavengers", "Graf Rats"),
    ("Mishra, Claimed by Gix", "Phyrexian Dragon Engine"),
    ("Phyrexian Dragon Engine", "Mishra, Claimed by Gix"),
    ("The Mightstone and Weakstone", "Urza, Lord Protector"),
    ("Titania, Voice of Gaea", "Argoth, Sanctum of Nature"),
    ("Urza, Lord Protector", "The Mightstone and Weakstone"),
    ("Vanille, Cheerful l'Cie", "Fang, Fearless l'Cie"),
];
