pub use ironsmith_core::{
    EXPLOITED_TAG, EXPLOITER_TAG, MANIFEST_DREAD_GRAVEYARD_TAG, PRIOR_EXILED_CARD_TAG,
    REVEALED_THIS_WAY_TAG, SOURCE_EXILED_TAG, SOURCE_OBJECT_TAG, TagKey,
};

/// Stable compiler-owned identities for recurring semantic bindings.
///
/// Grammar and reference resolution use these variants instead of inventing
/// string keys at individual recognition sites. Conversion to the runtime's
/// dynamic [`TagKey`] is confined to this explicit materialization boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CompilerReferenceTag {
    Triggering,
    Enchanted,
    Equipped,
    DivvySource,
    DivvyChosen,
    DivvyPile,
    LastRevealed,
    Sacrificed0,
    Targeted0,
    Targeted1,
    Keep,
    Damaged0,
    Damaged,
    TriggeringSource,
    TriggeringPermanentSpell,
    SearchLibrarySlotsProgress,
    PublicRevealed,
    ChosenObjects,
    SacrificeCost0,
    TapCost0,
    ModularTriggeringObject,
    ExaltedAttacker,
    DiscardedThisWay,
    DiscardedCost,
    ConvokedThisSpell,
    ChosenForEachPlayer,
    RevealedLibrary,
    It,
    DelegatedLibraryChooser,
    ChosenName,
    Chosen,
    VotedWithYou,
    VotedAgainstYou,
    SearchedOutsideGame,
    SearchedMultiZone,
    Searched,
    SameNameReference,
    SaddledItThisTurn,
    CrewedItThisTurn,
    RevealUntilLandRevealed,
    RevealUntilLandMatched,
    ReturnedControlLoss,
    Rest,
    PhaseOutSelection,
    OutsideGameOrExileSelected,
    OathRevealed,
    OathCreature,
    MultiZoneSearchChosen,
    LivingWeaponCreated,
    JunkExiledCard,
    JointDiscardOrSacrifice,
    IterativeLibraryExiled,
    IterativeLibraryCurrent,
    HideawayLooked,
    HideawayExiled,
    GraftEnteredCreature,
    ForMirrodinCreated,
    ExchangePlayerOne,
    ExchangePlayerTwo,
    ExchangeCreaturesOne,
    ExchangeCreaturesTwo,
    EachPlayerShuffled,
    EachPlayerQualifyingShuffled,
    EachPlayerConsultRevealed,
    EachPlayerConsultMatched,
    ControllerConsultRevealed,
    ControllerConsultMatched,
    DivvyOpponent,
    DemonstrateOpponent,
    Blocking,
    Blocked,
    ChosenDiscardingOpponent,
    ChosenCounteredExileSpell,
    BeheldCost0,
    BeheldChosenType,
    GiftedPlayer,
    WhereXCommanderManaValue,
    SourceExiled,
    MillProbe,
    EachPlayerRevealedThisWay,
    EachGraveyardChosen,
    DrawnRevealedCard,
    DelayedOwnedExiledChoice,
    CostExiledTop,
    CopiedStackObject,
    ChosenHandSpellToCast,
    ChosenCastFromGraveyard,
    ChosenCastFromAmong,
}

impl CompilerReferenceTag {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Triggering => "triggering",
            Self::Enchanted => "enchanted",
            Self::Equipped => "equipped",
            Self::DivvySource => "divvy_source",
            Self::DivvyChosen => "divvy_chosen",
            Self::DivvyPile => "divvy_pile",
            Self::LastRevealed => "__last_revealed__",
            Self::Sacrificed0 => "sacrificed_0",
            Self::Targeted0 => "targeted_0",
            Self::Targeted1 => "targeted_1",
            Self::Keep => "keep",
            Self::Damaged0 => "damaged_0",
            Self::Damaged => "damaged",
            Self::TriggeringSource => "triggering_source",
            Self::TriggeringPermanentSpell => "triggering_permanent_spell",
            Self::SearchLibrarySlotsProgress => "search_library_slots_progress",
            Self::PublicRevealed => "__public_revealed",
            Self::ChosenObjects => "__chosen_objects__",
            Self::SacrificeCost0 => "sacrifice_cost_0",
            Self::TapCost0 => "tap_cost_0",
            Self::ModularTriggeringObject => "modular_triggering_object",
            Self::ExaltedAttacker => "exalted_attacker",
            Self::DiscardedThisWay => "discarded_this_way",
            Self::DiscardedCost => "discarded_cost",
            Self::ConvokedThisSpell => "convoked_this_spell",
            Self::ChosenForEachPlayer => "chosen_for_each_player",
            Self::RevealedLibrary => "__revealed_library__",
            Self::It => "__it__",
            Self::DelegatedLibraryChooser => "__delegated_library_chooser__",
            Self::ChosenName => "__chosen_name__",
            Self::Chosen => "chosen",
            Self::VotedWithYou => "voted_with_you",
            Self::VotedAgainstYou => "voted_against_you",
            Self::SearchedOutsideGame => "searched_outside_game",
            Self::SearchedMultiZone => "searched_multi_zone",
            Self::Searched => "searched",
            Self::SameNameReference => "same_name_reference",
            Self::SaddledItThisTurn => "saddled_it_this_turn",
            Self::CrewedItThisTurn => "crewed_it_this_turn",
            Self::RevealUntilLandRevealed => "reveal_until_land_revealed",
            Self::RevealUntilLandMatched => "reveal_until_land_matched",
            Self::ReturnedControlLoss => "returned_control_loss",
            Self::Rest => "rest",
            Self::PhaseOutSelection => "phase_out_selection",
            Self::OutsideGameOrExileSelected => "outside_game_or_exile_selected",
            Self::OathRevealed => "oath_revealed",
            Self::OathCreature => "oath_creature",
            Self::MultiZoneSearchChosen => "multi_zone_search_chosen",
            Self::LivingWeaponCreated => "living_weapon_created",
            Self::JunkExiledCard => "junk_exiled_card",
            Self::JointDiscardOrSacrifice => "joint_discard_or_sacrifice",
            Self::IterativeLibraryExiled => "iterative_library_exiled",
            Self::IterativeLibraryCurrent => "iterative_library_current",
            Self::HideawayLooked => "hideaway_looked",
            Self::HideawayExiled => "hideaway_exiled",
            Self::GraftEnteredCreature => "graft_entered_creature",
            Self::ForMirrodinCreated => "for_mirrodin_created",
            Self::ExchangePlayerOne => "exchange_player_one",
            Self::ExchangePlayerTwo => "exchange_player_two",
            Self::ExchangeCreaturesOne => "exchange_creatures_one",
            Self::ExchangeCreaturesTwo => "exchange_creatures_two",
            Self::EachPlayerShuffled => "each_player_shuffled",
            Self::EachPlayerQualifyingShuffled => "each_player_qualifying_shuffled",
            Self::EachPlayerConsultRevealed => "each_player_consult_revealed",
            Self::EachPlayerConsultMatched => "each_player_consult_matched",
            Self::ControllerConsultRevealed => "controller_consult_revealed",
            Self::ControllerConsultMatched => "controller_consult_matched",
            Self::DivvyOpponent => "divvy_opponent",
            Self::DemonstrateOpponent => "demonstrate_opponent",
            Self::Blocking => "blocking",
            Self::Blocked => "blocked",
            Self::ChosenDiscardingOpponent => "chosen_discarding_opponent",
            Self::ChosenCounteredExileSpell => "chosen_countered_exile_spell",
            Self::BeheldCost0 => "beheld_cost_0",
            Self::BeheldChosenType => "beheld_chosen_type",
            Self::GiftedPlayer => "gifted_player",
            Self::WhereXCommanderManaValue => "__where_x_commander_mana_value",
            Self::SourceExiled => "__source_exiled__",
            Self::MillProbe => "__mill_probe__",
            Self::EachPlayerRevealedThisWay => "__each_player_revealed_this_way",
            Self::EachGraveyardChosen => "__each_graveyard_chosen",
            Self::DrawnRevealedCard => "__drawn_revealed_card__",
            Self::DelayedOwnedExiledChoice => "__delayed_owned_exiled_choice",
            Self::CostExiledTop => "__cost_exiled_top__",
            Self::CopiedStackObject => "__copied_stack_object__",
            Self::ChosenHandSpellToCast => "__chosen_hand_spell_to_cast",
            Self::ChosenCastFromGraveyard => "__chosen_cast_from_graveyard",
            Self::ChosenCastFromAmong => "__chosen_cast_from_among",
        }
    }

    pub fn key(self) -> TagKey {
        TagKey::new(self.as_str())
    }
}
