[package]
name = "ironsmith-compiler-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
ironsmith-core = { path = "../ironsmith-core", default-features = false, features = ["serde"] }
ironsmith-compiler-api = { path = "../ironsmith-compiler-api", default-features = false }
ironsmith-compiler-source = { path = "../ironsmith-compiler-source", default-features = false }

[features]
default = []

[lib]
path = "src/lib.rs"
