#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KeywordActionKind {
    Sticker,
    Amass,
    ArtSticker,
    AbilitySticker,
    PowerToughnessSticker,
    Bolster,
    Clash,
    CommitCrime,
    Craft,
    Crew,
    Cycle,
    Convoke,
    Discover,
    CompleteDungeon,
    Evolve,
    Earthbend,
    Explore,
    Exploit,
    Exert,
    Expend,
    Fateseal,
    Fight,
    Forage,
    Improvise,
    Incubate,
    Investigate,
    Manifest,
    NameSticker,
    Populate,
    RingTemptsYou,
    Renown,
    Connive,
    Proliferate,
    Support,
    Scry,
    Surveil,
    Train,
    UnlockDoor,
    Vote,
}

impl KeywordActionKind {
    pub fn from_trigger_word(word: &str) -> Option<Self> {
        match word {
            "sticker" | "stickers" | "stickered" => Some(Self::Sticker),
            "amass" | "amasses" | "amassed" | "amassing" => Some(Self::Amass),
            "bolster" | "bolsters" | "bolstered" | "bolstering" => Some(Self::Bolster),
            "clash" | "clashes" | "clashed" | "clashing" => Some(Self::Clash),
            "crime" | "crimes" => Some(Self::CommitCrime),
            "craft" | "crafts" | "crafted" | "crafting" => Some(Self::Craft),
            "crew" | "crews" | "crewed" | "crewing" => Some(Self::Crew),
            "cycle" | "cycles" | "cycled" => Some(Self::Cycle),
            "cycling" => Some(Self::Cycle),
            "convoke" | "convokes" | "convoked" => Some(Self::Convoke),
            "discover" | "discovers" | "discovered" | "discovering" => Some(Self::Discover),
            "complete" | "completes" | "completed" | "completing" => Some(Self::CompleteDungeon),
            "evolve" | "evolves" | "evolved" | "evolving" => Some(Self::Evolve),
            "earthbend" | "earthbends" => Some(Self::Earthbend),
            "explore" | "explores" | "explored" | "exploring" => Some(Self::Explore),
            "exploit" | "exploits" | "exploited" | "exploiting" => Some(Self::Exploit),
            "exert" | "exerts" | "exerted" | "exerting" => Some(Self::Exert),
            "expend" | "expends" | "expended" => Some(Self::Expend),
            "fateseal" | "fateseals" | "fatesealed" | "fatesealing" => Some(Self::Fateseal),
            "fight" | "fights" | "fought" | "fighting" => Some(Self::Fight),
            "forage" | "forages" | "foraged" | "foraging" => Some(Self::Forage),
            "improvise" | "improvises" | "improvised" => Some(Self::Improvise),
            "incubate" | "incubates" | "incubated" | "incubating" => Some(Self::Incubate),
            "investigate" | "investigates" => Some(Self::Investigate),
            "manifest" | "manifests" | "manifested" | "manifesting" => Some(Self::Manifest),
            "populate" | "populates" | "populated" | "populating" => Some(Self::Populate),
            "renown" | "renowned" => Some(Self::Renown),
            "connive" | "connives" | "connived" => Some(Self::Connive),
            "proliferate" | "proliferates" => Some(Self::Proliferate),
            "support" | "supports" | "supported" | "supporting" => Some(Self::Support),
            "scry" | "scries" => Some(Self::Scry),
            "surveil" | "surveils" => Some(Self::Surveil),
            "train" | "trains" | "trained" | "training" => Some(Self::Train),
            "unlock" | "unlocks" | "unlocked" | "unlocking" => Some(Self::UnlockDoor),
            "vote" | "votes" | "voting" => Some(Self::Vote),
            _ => None,
        }
    }

    pub fn infinitive(self) -> &'static str {
        match self {
            Self::Sticker => "put a sticker",
            Self::Amass => "amass",
            Self::ArtSticker => "put an art sticker",
            Self::AbilitySticker => "put an ability sticker",
            Self::PowerToughnessSticker => "put a power and toughness sticker",
            Self::Bolster => "bolster",
            Self::Clash => "clash",
            Self::CommitCrime => "commit a crime",
            Self::Craft => "craft",
            Self::Crew => "crew",
            Self::Cycle => "cycle",
            Self::Convoke => "convoke",
            Self::Discover => "discover",
            Self::CompleteDungeon => "complete a dungeon",
            Self::Evolve => "evolve",
            Self::Earthbend => "earthbend",
            Self::Explore => "explore",
            Self::Exploit => "exploit",
            Self::Exert => "exert",
            Self::Expend => "expend",
            Self::Fateseal => "fateseal",
            Self::Fight => "fight",
            Self::Forage => "forage",
            Self::Improvise => "improvise",
            Self::Incubate => "incubate",
            Self::Investigate => "investigate",
            Self::Manifest => "manifest",
            Self::Populate => "populate",
            Self::NameSticker => "put a name sticker",
            Self::RingTemptsYou => "have the Ring tempt you",
            Self::Renown => "become renowned",
            Self::Connive => "connive",
            Self::Proliferate => "proliferate",
            Self::Support => "support",
            Self::Scry => "scry",
            Self::Surveil => "surveil",
            Self::Train => "train",
            Self::UnlockDoor => "unlock this door",
            Self::Vote => "vote",
        }
    }

    pub fn third_person(self) -> &'static str {
        match self {
            Self::Sticker => "puts a sticker",
            Self::Amass => "amasses",
            Self::ArtSticker => "puts an art sticker",
            Self::AbilitySticker => "puts an ability sticker",
            Self::PowerToughnessSticker => "puts a power and toughness sticker",
            Self::Bolster => "bolsters",
            Self::Clash => "clashes",
            Self::CommitCrime => "commits a crime",
            Self::Craft => "crafts",
            Self::Crew => "crews",
            Self::Cycle => "cycles",
            Self::Convoke => "convokes",
            Self::Discover => "discovers",
            Self::CompleteDungeon => "completes a dungeon",
            Self::Evolve => "evolves",
            Self::Earthbend => "earthbends",
            Self::Explore => "explores",
            Self::Exploit => "exploits",
            Self::Exert => "exerts",
            Self::Expend => "expends",
            Self::Fateseal => "fateseals",
            Self::Fight => "fights",
            Self::Forage => "forages",
            Self::Improvise => "improvises",
            Self::Incubate => "incubates",
            Self::Investigate => "investigates",
            Self::Manifest => "manifests",
            Self::Populate => "populates",
            Self::NameSticker => "puts a name sticker",
            Self::RingTemptsYou => "has the Ring tempt them",
            Self::Renown => "becomes renowned",
            Self::Connive => "connives",
            Self::Proliferate => "proliferates",
            Self::Support => "supports",
            Self::Scry => "scries",
            Self::Surveil => "surveils",
            Self::Train => "trains",
            Self::UnlockDoor => "unlocks this door",
            Self::Vote => "votes",
        }
    }
}
