[package]
name = "ironsmith-verifier-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
ironsmith-verifier = { path = "../ironsmith-verifier", default-features = false }
ironsmith-verifier-ziffle = { path = "../ironsmith-verifier-ziffle", default-features = false }
ironsmith-verifier-wasm-api = { path = "../ironsmith-verifier-wasm-api", default-features = false }
wasm-bindgen = "0.2.120"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O1"]
