[package]
name = "ironsmith-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
ironsmith-compiler-grammar = { path = "../ironsmith-compiler-grammar", default-features = false }

[dev-dependencies]
ironsmith-core = { path = "../ironsmith-core" }

[features]
default = []
serialization = ["ironsmith-compiler-grammar/serialization"]

[lib]
path = "src/lib.rs"
